/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bank.project;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author gulshaneng
 */
public class Deposit extends javax.swing.JFrame {

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        this.setSize(680, 150);
    }
        Connection con;
       Statement st;
       ResultSet rs;
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account_number = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        generate_detail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        ctype = new javax.swing.JLabel();
        fathername = new javax.swing.JLabel();
        deposit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deposit");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(account_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 30, 201, -1));

        amount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount.setEnabled(false);
        amount.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                amountInputMethodTextChanged(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 65, 199, -1));

        generate_detail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate_detail.setText("Generate Detail");
        generate_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_detailActionPerformed(evt);
            }
        });
        getContentPane().add(generate_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 27, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Account Number ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 33, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, 121, -1));

        jLabel3.setText("Customer Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel4.setText("Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setText("Date of Birth :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel8.setText("Country Name :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel9.setText("Father's Name :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        gender.setFocusable(false);
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 150, 20));

        name.setFocusable(false);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 20));

        dob.setFocusable(false);
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 150, 20));

        country.setFocusable(false);
        getContentPane().add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, 20));

        ctype.setFocusable(false);
        getContentPane().add(ctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 150, 20));

        fathername.setFocusable(false);
        getContentPane().add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 150, 20));

        deposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deposit.setText("Deposit Balance");
        deposit.setEnabled(false);
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 64, 151, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
    }//GEN-LAST:event_formWindowClosing

    private void generate_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_detailActionPerformed
    String accountNumber=account_number.getText();
       if(accountNumber!="")
           {
                this.setSize(675, 250);
                amount.setEnabled(true);
           }
       try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","jaihanuman");
           st=con.createStatement();
           String Query="select * from account where account_number=?";
           PreparedStatement ps=con.prepareCall(Query);
           ps.setString(1, accountNumber);
           rs=ps.executeQuery();
           if(!rs.next())
            {
                JOptionPane.showMessageDialog(null, "Enter valid account number !!");
                account_number.setText("");
            }
           else
           {
              ctype.setText(rs.getString("customer_type"));
               name.setText(rs.getString("name"));
              dob.setText(rs.getString("dob"));
              gender.setText(rs.getString("gender"));
              country.setText(rs.getString("country_name"));
              fathername.setText(rs.getString("father_name"));
              
           }
           
          
       }catch(Exception e){}// TODO add your handling code here:
    }//GEN-LAST:event_generate_detailActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
      String accountNumber=account_number.getText();
      Integer balance=Integer.valueOf(amount.getText());
         try{
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","jaihanuman");
           st=con.createStatement();
           String Query="update account set balance=balance + ? where account_number=?";
           PreparedStatement ps=con.prepareStatement(Query);
           ps.setInt(1, balance);
           ps.setString(2, accountNumber);
           ps.executeUpdate();
            String Query2="insert into deposit (account_number,name,date,deposit_amount, avail_bal) values (?,?,?,?,(select account.balance from account where account.account_number=?))";
           PreparedStatement ps2=con.prepareStatement(Query2);
             ps2.setString(1, accountNumber);
           ps2.setString(2,rs.getString("name"));
         //to insert date
           DateFormat df = new SimpleDateFormat("dd/MM/yy");
            java.util.Date dateobj =new java.util.Date(); 
            java.sql.Date deposit_date=new java.sql.Date(dateobj.getTime());
   
              ps2.setDate(3, deposit_date);
              ps2.setInt(4, balance);
              ps2.setString(5,accountNumber);
              ps2.execute();
              JOptionPane.showMessageDialog(null,"Sucessfully Deposited");
              con.close();
              this.dispose();
       }catch(Exception e){System.out.print(e.getMessage());}
      
    }//GEN-LAST:event_depositActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
     Admin c=new Admin();
       c.setVisible(true); 
       //System.out.print(this.getSize());// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void amountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_amountInputMethodTextChanged
      
    }//GEN-LAST:event_amountInputMethodTextChanged

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        deposit.setEnabled(true);
    }//GEN-LAST:event_amountKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setSize(675, 150);
      
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_number;
    private javax.swing.JTextField amount;
    public javax.swing.JLabel country;
    public javax.swing.JLabel ctype;
    public javax.swing.JButton deposit;
    public javax.swing.JLabel dob;
    public javax.swing.JLabel fathername;
    public javax.swing.JLabel gender;
    public javax.swing.JButton generate_detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
