/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bank.project;
import java.sql.*;
import java.text.*;
import javax.swing.JOptionPane;
/**
 *
 * @author gulshaneng
 */
public class WithDraw extends javax.swing.JFrame {

    /**
     * Creates new form WithDraw
     */
    public WithDraw() {
        initComponents();
        this.setSize(680, 150);
    }
 Connection con;
       Statement st;
       ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account_number = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        generate_detail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        ctype = new javax.swing.JLabel();
        fathername = new javax.swing.JLabel();
        withdraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        account_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(account_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 34, 201, -1));

        amount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount.setEnabled(false);
        amount.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                amountInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 69, 199, -1));

        generate_detail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generate_detail.setText("Generate Detail");
        generate_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_detailActionPerformed(evt);
            }
        });
        getContentPane().add(generate_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 31, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Account Number ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 72, 121, -1));

        jLabel3.setText("Customer Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 124, -1, -1));

        jLabel4.setText("Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 124, -1, -1));

        jLabel5.setText("Date of Birth :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 154, -1, -1));

        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 184, -1, -1));

        jLabel8.setText("Country Name :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 184, -1, -1));

        jLabel9.setText("Father's Name :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 154, -1, -1));

        gender.setFocusable(false);
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 184, 150, 20));

        name.setFocusable(false);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 124, 150, 20));

        dob.setFocusable(false);
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 154, 150, 20));

        country.setFocusable(false);
        getContentPane().add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 184, 150, 20));

        ctype.setFocusable(false);
        getContentPane().add(ctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 124, 150, 20));

        fathername.setFocusable(false);
        getContentPane().add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 154, 150, 20));

        withdraw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdraw.setText("WithDraw Balance");
        withdraw.setEnabled(false);
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 68, 151, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_amountInputMethodTextChanged

    }//GEN-LAST:event_amountInputMethodTextChanged

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        withdraw.setEnabled(true);
    }//GEN-LAST:event_amountKeyTyped

    private void generate_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_detailActionPerformed
       String accountNumber=account_number.getText();
        if(accountNumber!=null)
           {
                this.setSize(680, 260);
                amount.setEnabled(true);
           }
            else
            this.setSize(680, 150);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","jaihanuman");
            st=con.createStatement();
            String Query="select * from account where account_number=?";
            PreparedStatement ps=con.prepareCall(Query);
            ps.setString(1, accountNumber);
            rs=ps.executeQuery();
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null, "Enter valid account number !!");
                account_number.setText("");
            }
           else
            {
                ctype.setText(rs.getString("customer_type"));
                name.setText(rs.getString("name"));
                dob.setText(rs.getString("dob"));
                gender.setText(rs.getString("gender"));
                country.setText(rs.getString("country_name"));
                fathername.setText(rs.getString("father_name"));

            }
            

        }catch(Exception e){}// TODO add your handling code here:
    }//GEN-LAST:event_generate_detailActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        String accountNumber=account_number.getText();
        Integer balance=Integer.valueOf(amount.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","jaihanuman");
            st=con.createStatement();
            String Query="update account set balance=balance - ? where account_number=?";
            PreparedStatement ps=con.prepareStatement(Query);
            ps.setInt(1, balance);
            ps.setString(2, accountNumber);
            ps.executeUpdate();
            String Query2="insert into withdraw (account_number,name,date,withdraw_amount, avail_bal) values (?,?,?,?,(select account.balance from account where account.account_number=?))";
            PreparedStatement ps2=con.prepareStatement(Query2);
            ps2.setString(1, accountNumber);
            ps2.setString(2,rs.getString("name"));
            //to insert date
            DateFormat df = new SimpleDateFormat("dd/MM/yy");
            java.util.Date dateobj =new java.util.Date();
            java.sql.Date deposit_date=new java.sql.Date(dateobj.getTime());

            ps2.setDate(3, deposit_date);
            ps2.setInt(4, balance);
             ps2.setString(5,accountNumber);
            ps2.execute();
            JOptionPane.showMessageDialog(null,"With draw Sucessfull");
            con.close();
            this.dispose();
            Admin a=new Admin();
            a.setVisible(true);
        }catch(Exception e){System.out.print(e);}

    }//GEN-LAST:event_withdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithDraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithDraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_number;
    private javax.swing.JTextField amount;
    public javax.swing.JLabel country;
    public javax.swing.JLabel ctype;
    public javax.swing.JLabel dob;
    public javax.swing.JLabel fathername;
    public javax.swing.JLabel gender;
    public javax.swing.JButton generate_detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel name;
    public javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
